export interface OutputLine {
  text: string
  type: 'command' | 'info' | 'success' | 'warning' | 'error' | 'progress' | 'blank'
  delay: number
  progress?: number
}

export interface RepairTool {
  id: string
  name: string
  icon: string
  category: 'system' | 'network' | 'disk' | 'maintenance' | 'security' | 'info'
  description: string
  command: string
  estimatedTime: number
  dangerLevel: 'safe' | 'moderate' | 'caution'
  tags: string[]
  outputLines: OutputLine[]
}

export const REPAIR_TOOLS: RepairTool[] = [
  {
    id: 'sfc',
    name: 'SFC Scan',
    icon: 'Shield',
    category: 'system',
    description: 'Scans integrity of all protected system files and repairs corrupt files.',
    command: 'sfc /scannow',
    estimatedTime: 15,
    dangerLevel: 'safe',
    tags: ['system', 'repair', 'files'],
    outputLines: [
      { text: 'Microsoft Windows [Version 10.0.19045.4291]', type: 'info', delay: 0 },
      { text: '(c) Microsoft Corporation. All rights reserved.', type: 'info', delay: 100 },
      { text: '', type: 'blank', delay: 200 },
      { text: 'C:\\Windows\\system32>sfc /scannow', type: 'command', delay: 400 },
      { text: '', type: 'blank', delay: 600 },
      { text: 'Beginning system scan.  This process will take some time.', type: 'info', delay: 900 },
      { text: '', type: 'blank', delay: 1100 },
      { text: 'Beginning verification phase of system scan.', type: 'info', delay: 1500 },
      { text: 'Verification  5% complete.', type: 'progress', delay: 2000, progress: 5 },
      { text: 'Verification 10% complete.', type: 'progress', delay: 3000, progress: 10 },
      { text: 'Verification 20% complete.', type: 'progress', delay: 4500, progress: 20 },
      { text: 'Verification 30% complete.', type: 'progress', delay: 6000, progress: 30 },
      { text: 'Verification 40% complete.', type: 'progress', delay: 7200, progress: 40 },
      { text: 'Verification 50% complete.', type: 'progress', delay: 8500, progress: 50 },
      { text: 'Verification 60% complete.', type: 'progress', delay: 9800, progress: 60 },
      { text: 'Verification 70% complete.', type: 'progress', delay: 11000, progress: 70 },
      { text: 'Verification 80% complete.', type: 'progress', delay: 12200, progress: 80 },
      { text: 'Verification 90% complete.', type: 'progress', delay: 13400, progress: 90 },
      { text: 'Verification 100% complete.', type: 'progress', delay: 14600, progress: 100 },
      { text: '', type: 'blank', delay: 14800 },
      { text: 'Windows Resource Protection found corrupt files and successfully repaired them.', type: 'success', delay: 15100 },
      { text: 'Details are included in the CBS.Log windir\\Logs\\CBS\\CBS.log', type: 'info', delay: 15500 },
      { text: 'For online repairs, the servicing stack log file is at', type: 'info', delay: 15800 },
      { text: 'C:\\Windows\\Logs\\CBS\\CBS.log', type: 'info', delay: 16100 },
      { text: '', type: 'blank', delay: 16400 },
      { text: '[ COMPLETED ] SFC scan finished. System files repaired successfully.', type: 'success', delay: 16700 },
    ]
  },
  {
    id: 'dism',
    name: 'DISM Repair',
    icon: 'Wrench',
    category: 'system',
    description: 'Repairs the Windows system image and restores component store health.',
    command: 'DISM /Online /Cleanup-Image /RestoreHealth',
    estimatedTime: 20,
    dangerLevel: 'safe',
    tags: ['system', 'image', 'repair'],
    outputLines: [
      { text: 'C:\\Windows\\system32>DISM /Online /Cleanup-Image /RestoreHealth', type: 'command', delay: 0 },
      { text: '', type: 'blank', delay: 300 },
      { text: 'Deployment Image Servicing and Management tool', type: 'info', delay: 600 },
      { text: 'Version: 10.0.19041.3636', type: 'info', delay: 900 },
      { text: '', type: 'blank', delay: 1100 },
      { text: 'Image Version: 10.0.19045.4291', type: 'info', delay: 1400 },
      { text: '', type: 'blank', delay: 1700 },
      { text: '[==                           ]  5.0%', type: 'progress', delay: 2000, progress: 5 },
      { text: '[=====                        ] 15.0%', type: 'progress', delay: 4000, progress: 15 },
      { text: '[=========                    ] 30.0%', type: 'progress', delay: 7000, progress: 30 },
      { text: '[=============                ] 45.0%', type: 'progress', delay: 10000, progress: 45 },
      { text: '[==================           ] 60.0%', type: 'progress', delay: 13000, progress: 60 },
      { text: '[=======================      ] 75.0%', type: 'progress', delay: 16000, progress: 75 },
      { text: '[===========================  ] 90.0%', type: 'progress', delay: 18000, progress: 90 },
      { text: '[============================] 100.0%', type: 'progress', delay: 19500, progress: 100 },
      { text: '', type: 'blank', delay: 19800 },
      { text: 'The restore operation completed successfully.', type: 'success', delay: 20000 },
      { text: 'The operation completed successfully.', type: 'success', delay: 20400 },
      { text: '', type: 'blank', delay: 20700 },
      { text: '[ COMPLETED ] DISM repair done. Windows health restored.', type: 'success', delay: 21000 },
    ]
  },
  {
    id: 'dns',
    name: 'DNS Flush',
    icon: 'Globe',
    category: 'network',
    description: 'Flushes the DNS resolver cache to fix DNS-related connectivity issues.',
    command: 'ipconfig /flushdns',
    estimatedTime: 2,
    dangerLevel: 'safe',
    tags: ['network', 'dns', 'cache'],
    outputLines: [
      { text: 'C:\\Windows\\system32>ipconfig /flushdns', type: 'command', delay: 0 },
      { text: '', type: 'blank', delay: 200 },
      { text: 'Windows IP Configuration', type: 'info', delay: 500 },
      { text: '', type: 'blank', delay: 700 },
      { text: 'Successfully flushed the DNS Resolver Cache.', type: 'success', delay: 900 },
      { text: '', type: 'blank', delay: 1100 },
      { text: '[ COMPLETED ] DNS cache cleared. 1,247 entries removed.', type: 'success', delay: 1400 },
    ]
  },
  {
    id: 'network-reset',
    name: 'Network Reset',
    icon: 'Network',
    category: 'network',
    description: 'Resets Winsock catalog and TCP/IP stack to default configuration.',
    command: 'netsh winsock reset && netsh int ip reset',
    estimatedTime: 6,
    dangerLevel: 'moderate',
    tags: ['network', 'winsock', 'tcp', 'reset'],
    outputLines: [
      { text: 'C:\\Windows\\system32>netsh winsock reset', type: 'command', delay: 0 },
      { text: '', type: 'blank', delay: 300 },
      { text: 'Successfully reset the Winsock Catalog.', type: 'success', delay: 700 },
      { text: 'You must restart the computer in order to complete the reset.', type: 'warning', delay: 1000 },
      { text: '', type: 'blank', delay: 1300 },
      { text: 'C:\\Windows\\system32>netsh int ip reset', type: 'command', delay: 1600 },
      { text: '', type: 'blank', delay: 1900 },
      { text: 'Resetting Interface, OK!', type: 'success', delay: 2400 },
      { text: 'Resetting , OK!', type: 'success', delay: 2800 },
      { text: 'Resetting Global, OK!', type: 'success', delay: 3200 },
      { text: 'Resetting Interface, OK!', type: 'success', delay: 3600 },
      { text: '', type: 'blank', delay: 4000 },
      { text: 'Restart the computer to complete this action.', type: 'warning', delay: 4400 },
      { text: '', type: 'blank', delay: 4700 },
      { text: '[ COMPLETED ] Network stack reset. Restart required to apply changes.', type: 'success', delay: 5200 },
    ]
  },
  {
    id: 'ip-renew',
    name: 'IP Release/Renew',
    icon: 'RefreshCw',
    category: 'network',
    description: 'Releases current IP address and requests a new lease from DHCP server.',
    command: 'ipconfig /release && ipconfig /renew',
    estimatedTime: 8,
    dangerLevel: 'moderate',
    tags: ['network', 'ip', 'dhcp'],
    outputLines: [
      { text: 'C:\\Windows\\system32>ipconfig /release', type: 'command', delay: 0 },
      { text: '', type: 'blank', delay: 300 },
      { text: 'Windows IP Configuration', type: 'info', delay: 600 },
      { text: '', type: 'blank', delay: 800 },
      { text: 'Ethernet adapter Ethernet 0:', type: 'info', delay: 1100 },
      { text: '   Connection-specific DNS Suffix  . :', type: 'info', delay: 1400 },
      { text: '   IPv4 Address. . . . . . . . . . . : 0.0.0.0', type: 'info', delay: 1700 },
      { text: '   Subnet Mask . . . . . . . . . . . : 0.0.0.0', type: 'info', delay: 2000 },
      { text: '   Default Gateway . . . . . . . . . :', type: 'info', delay: 2300 },
      { text: '', type: 'blank', delay: 2600 },
      { text: 'C:\\Windows\\system32>ipconfig /renew', type: 'command', delay: 2900 },
      { text: '', type: 'blank', delay: 3200 },
      { text: 'Windows IP Configuration', type: 'info', delay: 3500 },
      { text: '', type: 'blank', delay: 3800 },
      { text: 'Ethernet adapter Ethernet 0:', type: 'info', delay: 4100 },
      { text: '   Connection-specific DNS Suffix  . : corp.local', type: 'info', delay: 4400 },
      { text: '   IPv4 Address. . . . . . . . . . . : 192.168.1.105', type: 'success', delay: 5000 },
      { text: '   Subnet Mask . . . . . . . . . . . : 255.255.255.0', type: 'info', delay: 5400 },
      { text: '   Default Gateway . . . . . . . . . : 192.168.1.1', type: 'info', delay: 5800 },
      { text: '', type: 'blank', delay: 6200 },
      { text: '[ COMPLETED ] IP renewed. Connected as 192.168.1.105 via DHCP.', type: 'success', delay: 6700 },
    ]
  },
  {
    id: 'chkdsk',
    name: 'Disk Health Check',
    icon: 'HardDrive',
    category: 'disk',
    description: 'Scans C: drive for file system errors and bad sectors.',
    command: 'chkdsk C: /f /r /x',
    estimatedTime: 14,
    dangerLevel: 'moderate',
    tags: ['disk', 'health', 'ntfs', 'errors'],
    outputLines: [
      { text: 'C:\\Windows\\system32>chkdsk C: /f /r /x', type: 'command', delay: 0 },
      { text: '', type: 'blank', delay: 300 },
      { text: 'The type of the file system is NTFS.', type: 'info', delay: 600 },
      { text: 'Volume label is Windows (C:).', type: 'info', delay: 900 },
      { text: 'Volume dismounted. All opened handles to this volume are now invalid.', type: 'warning', delay: 1200 },
      { text: '', type: 'blank', delay: 1500 },
      { text: 'CHKDSK is verifying files (stage 1 of 5)...', type: 'info', delay: 1800 },
      { text: '  317440 file records processed.', type: 'progress', delay: 3000, progress: 20 },
      { text: 'File verification completed.', type: 'success', delay: 3500 },
      { text: '  0 large file records processed.', type: 'info', delay: 3800 },
      { text: '  0 bad file records processed.', type: 'info', delay: 4100 },
      { text: '', type: 'blank', delay: 4400 },
      { text: 'CHKDSK is verifying indexes (stage 2 of 5)...', type: 'info', delay: 4800 },
      { text: '  432986 index entries processed.', type: 'progress', delay: 6500, progress: 40 },
      { text: 'Index verification completed.', type: 'success', delay: 7000 },
      { text: '', type: 'blank', delay: 7300 },
      { text: 'CHKDSK is verifying security descriptors (stage 3 of 5)...', type: 'info', delay: 7700 },
      { text: '  317440 file SDs/SIDs processed.', type: 'progress', delay: 9200, progress: 60 },
      { text: 'Security descriptor verification completed.', type: 'success', delay: 9700 },
      { text: '', type: 'blank', delay: 10000 },
      { text: 'CHKDSK is verifying file data (stage 4 of 5)...', type: 'info', delay: 10400 },
      { text: '  317424 files processed.', type: 'progress', delay: 11500, progress: 80 },
      { text: 'File data verification completed.', type: 'success', delay: 12000 },
      { text: '', type: 'blank', delay: 12300 },
      { text: 'CHKDSK is verifying free space (stage 5 of 5)...', type: 'info', delay: 12700 },
      { text: '  188211920 free clusters processed.', type: 'progress', delay: 13500, progress: 100 },
      { text: '', type: 'blank', delay: 13800 },
      { text: 'Windows has scanned the file system and found no problems.', type: 'success', delay: 14100 },
      { text: '  511704063 KB total disk space.    323492128 KB in use.', type: 'info', delay: 14400 },
      { text: '  188211935 KB available on disk.   4096 bytes in each allocation unit.', type: 'info', delay: 14700 },
      { text: '', type: 'blank', delay: 15000 },
      { text: '[ COMPLETED ] Disk check done. No critical errors found.', type: 'success', delay: 15300 },
    ]
  },
  {
    id: 'temp-clean',
    name: 'Temp File Cleaner',
    icon: 'Trash2',
    category: 'maintenance',
    description: 'Removes temporary files, browser cache, and system junk files.',
    command: 'del /q /f /s %TEMP%\\* && cleanmgr /sagerun:1',
    estimatedTime: 6,
    dangerLevel: 'safe',
    tags: ['cleanup', 'storage', 'temp', 'cache'],
    outputLines: [
      { text: 'C:\\Windows\\system32>del /q /f /s %TEMP%\\*', type: 'command', delay: 0 },
      { text: '', type: 'blank', delay: 300 },
      { text: 'Scanning temporary directories...', type: 'info', delay: 600 },
      { text: 'Found 3,247 files in %TEMP% (2.4 GB)', type: 'info', delay: 1200 },
      { text: 'Deleting C:\\Users\\Admin\\AppData\\Local\\Temp\\...', type: 'progress', delay: 1800, progress: 25 },
      { text: 'Deleted 891 files (850 MB freed)', type: 'success', delay: 2800 },
      { text: 'Deleting C:\\Windows\\Temp\\...', type: 'progress', delay: 3200, progress: 50 },
      { text: 'Deleted 1,124 files (1.1 GB freed)', type: 'success', delay: 4000 },
      { text: 'Clearing browser cache files...', type: 'progress', delay: 4400, progress: 75 },
      { text: 'Deleted 1,232 cache entries (500 MB freed)', type: 'success', delay: 5000 },
      { text: 'Cleaning prefetch files...', type: 'progress', delay: 5400, progress: 95 },
      { text: '', type: 'blank', delay: 5800 },
      { text: 'Total: 3,247 files removed. 2.45 GB of disk space freed.', type: 'success', delay: 6100 },
      { text: '', type: 'blank', delay: 6400 },
      { text: '[ COMPLETED ] Cleanup finished. 2.45 GB recovered.', type: 'success', delay: 6700 },
    ]
  },
  {
    id: 'win-activation',
    name: 'Activation Check',
    icon: 'Key',
    category: 'security',
    description: 'Verifies Windows activation status and license validity.',
    command: 'slmgr /xpr && slmgr /dlv',
    estimatedTime: 3,
    dangerLevel: 'safe',
    tags: ['activation', 'license', 'windows'],
    outputLines: [
      { text: 'C:\\Windows\\system32>slmgr /xpr', type: 'command', delay: 0 },
      { text: '', type: 'blank', delay: 300 },
      { text: 'Windows Script Host', type: 'info', delay: 600 },
      { text: '', type: 'blank', delay: 800 },
      { text: 'Name: Windows 10 Enterprise', type: 'info', delay: 1100 },
      { text: 'Description: Windows(R), VOLUME_MAK channel', type: 'info', delay: 1400 },
      { text: 'Partial Product Key: XXXXX-XXXXX-XXXXX-XXXXX-AB4F2', type: 'info', delay: 1700 },
      { text: 'License Status: Licensed', type: 'success', delay: 2000 },
      { text: 'The machine is permanently activated.', type: 'success', delay: 2400 },
      { text: '', type: 'blank', delay: 2700 },
      { text: '[ COMPLETED ] Windows is activated. Perpetual license valid.', type: 'success', delay: 3000 },
    ]
  },
  {
    id: 'antivirus-check',
    name: 'Antivirus Status',
    icon: 'ShieldCheck',
    category: 'security',
    description: 'Checks Windows Defender status, definitions, and real-time protection.',
    command: 'Get-MpComputerStatus | Select-Object AntispywareEnabled, RealTimeProtectionEnabled, AntivirusEnabled',
    estimatedTime: 4,
    dangerLevel: 'safe',
    tags: ['security', 'antivirus', 'defender'],
    outputLines: [
      { text: 'C:\\Windows\\system32>powershell -Command "Get-MpComputerStatus"', type: 'command', delay: 0 },
      { text: '', type: 'blank', delay: 300 },
      { text: 'Windows Defender Status Report', type: 'info', delay: 700 },
      { text: '─────────────────────────────────────────────', type: 'info', delay: 900 },
      { text: 'AMServiceEnabled          : True', type: 'success', delay: 1200 },
      { text: 'AntispywareEnabled        : True', type: 'success', delay: 1500 },
      { text: 'AntivirusEnabled          : True', type: 'success', delay: 1800 },
      { text: 'BehaviorMonitorEnabled    : True', type: 'success', delay: 2100 },
      { text: 'IoavProtectionEnabled     : True', type: 'success', delay: 2400 },
      { text: 'NISEnabled                : True', type: 'success', delay: 2700 },
      { text: 'OnAccessProtectionEnabled : True', type: 'success', delay: 3000 },
      { text: 'RealTimeProtectionEnabled : True', type: 'success', delay: 3300 },
      { text: 'AntivirusSignatureAge     : 0', type: 'success', delay: 3600 },
      { text: 'AntivirusSignatureVersion : 1.409.1265.0', type: 'info', delay: 3900 },
      { text: '', type: 'blank', delay: 4200 },
      { text: '[ COMPLETED ] Defender is active. All protections enabled. Definitions up-to-date.', type: 'success', delay: 4600 },
    ]
  },
  {
    id: 'system-info',
    name: 'System Information',
    icon: 'Monitor',
    category: 'info',
    description: 'Gathers detailed hardware, OS, and configuration information.',
    command: 'systeminfo && msinfo32',
    estimatedTime: 5,
    dangerLevel: 'safe',
    tags: ['info', 'hardware', 'os', 'diagnostics'],
    outputLines: [
      { text: 'C:\\Windows\\system32>systeminfo', type: 'command', delay: 0 },
      { text: '', type: 'blank', delay: 300 },
      { text: 'Host Name:                 WORKSTATION-01', type: 'info', delay: 600 },
      { text: 'OS Name:                   Microsoft Windows 10 Enterprise', type: 'info', delay: 900 },
      { text: 'OS Version:                10.0.19045 N/A Build 19045', type: 'info', delay: 1200 },
      { text: 'OS Manufacturer:           Microsoft Corporation', type: 'info', delay: 1500 },
      { text: 'OS Configuration:          Member Workstation', type: 'info', delay: 1800 },
      { text: 'OS Build Type:             Multiprocessor Free', type: 'info', delay: 2100 },
      { text: 'System Manufacturer:       Dell Inc.', type: 'info', delay: 2400 },
      { text: 'System Model:              OptiPlex 7090', type: 'info', delay: 2700 },
      { text: 'System Type:               x64-based PC', type: 'info', delay: 3000 },
      { text: 'Processor(s):              Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz', type: 'info', delay: 3300 },
      { text: 'Total Physical Memory:     32,768 MB', type: 'info', delay: 3600 },
      { text: 'Available Physical Memory: 18,432 MB', type: 'info', delay: 3900 },
      { text: 'Virtual Memory: Max Size:  65,536 MB', type: 'info', delay: 4200 },
      { text: 'Domain:                    corp.local', type: 'info', delay: 4500 },
      { text: 'Logon Server:              \\\\DC01', type: 'info', delay: 4800 },
      { text: '', type: 'blank', delay: 5100 },
      { text: '[ COMPLETED ] System information gathered successfully.', type: 'success', delay: 5400 },
    ]
  },
  {
    id: 'startup-apps',
    name: 'Startup Analyzer',
    icon: 'Zap',
    category: 'maintenance',
    description: 'Lists and analyzes all startup programs and their impact on boot time.',
    command: 'Get-CimInstance Win32_StartupCommand | Select-Object Name, Command, Location',
    estimatedTime: 4,
    dangerLevel: 'safe',
    tags: ['startup', 'performance', 'boot'],
    outputLines: [
      { text: 'C:\\Windows\\system32>powershell -Command "Get-CimInstance Win32_StartupCommand"', type: 'command', delay: 0 },
      { text: '', type: 'blank', delay: 300 },
      { text: 'Analyzing startup programs...', type: 'info', delay: 700 },
      { text: '', type: 'blank', delay: 900 },
      { text: 'Name                     Impact   Location', type: 'info', delay: 1200 },
      { text: '─────────────────────────────────────────────────', type: 'info', delay: 1400 },
      { text: 'Microsoft Teams          HIGH     HKCU\\Run', type: 'warning', delay: 1700 },
      { text: 'OneDrive                 MEDIUM   HKCU\\Run', type: 'warning', delay: 2000 },
      { text: 'Windows Security         LOW      HKLM\\Run', type: 'success', delay: 2300 },
      { text: 'Intel Graphics           LOW      HKLM\\Run', type: 'success', delay: 2600 },
      { text: 'Realtek HD Audio         LOW      HKLM\\Run', type: 'success', delay: 2900 },
      { text: 'Adobe Updater            MEDIUM   HKCU\\Run', type: 'warning', delay: 3200 },
      { text: 'Zoom Launcher            MEDIUM   HKCU\\Run', type: 'warning', delay: 3500 },
      { text: '', type: 'blank', delay: 3800 },
      { text: 'Total: 7 startup items found. 4 items causing slow boot.', type: 'warning', delay: 4100 },
      { text: 'Recommendation: Disable Teams & Adobe Updater from startup.', type: 'info', delay: 4500 },
      { text: '', type: 'blank', delay: 4800 },
      { text: '[ COMPLETED ] Startup analysis done. Consider disabling HIGH impact items.', type: 'success', delay: 5200 },
    ]
  },
  {
    id: 'driver-check',
    name: 'Driver Update Check',
    icon: 'Cpu',
    category: 'info',
    description: 'Scans for outdated, missing, or problematic device drivers.',
    command: 'Get-WmiObject Win32_PnPSignedDriver | Select-Object DeviceName, DriverVersion, DriverDate',
    estimatedTime: 6,
    dangerLevel: 'safe',
    tags: ['drivers', 'hardware', 'update'],
    outputLines: [
      { text: 'C:\\Windows\\system32>pnputil /scan-devices', type: 'command', delay: 0 },
      { text: '', type: 'blank', delay: 300 },
      { text: 'Microsoft PnP Utility', type: 'info', delay: 600 },
      { text: '', type: 'blank', delay: 800 },
      { text: 'Scanning for device driver updates...', type: 'info', delay: 1100 },
      { text: '', type: 'blank', delay: 1400 },
      { text: 'Device                    Status        Version', type: 'info', delay: 1700 },
      { text: '─────────────────────────────────────────────────────────', type: 'info', delay: 1900 },
      { text: '[OK] Intel Core i7        Up-to-date    10.1.19041.0', type: 'success', delay: 2300 },
      { text: '[OK] NVIDIA RTX 3080      Up-to-date    31.0.15.3540', type: 'success', delay: 2700 },
      { text: '[OK] Realtek Audio        Up-to-date    6.0.9260.1', type: 'success', delay: 3100 },
      { text: '[!!] Intel LAN Driver     UPDATE AVAIL  12.19.1.36', type: 'warning', delay: 3500 },
      { text: '[OK] USB 3.0 Host Ctrl    Up-to-date    10.0.19041.1', type: 'success', delay: 3900 },
      { text: '[!!] HP LaserJet Driver   UPDATE AVAIL  61.230.1.24876', type: 'warning', delay: 4300 },
      { text: '[OK] Bluetooth Adapter    Up-to-date    22.140.0.3', type: 'success', delay: 4700 },
      { text: '', type: 'blank', delay: 5100 },
      { text: '2 driver updates available. Visit Windows Update or manufacturer website.', type: 'warning', delay: 5400 },
      { text: '', type: 'blank', delay: 5700 },
      { text: '[ COMPLETED ] Driver scan complete. 2 updates recommended.', type: 'success', delay: 6100 },
    ]
  },
]

export const CATEGORIES = {
  system: { label: 'System Repair', color: 'text-terminal-cyan' },
  network: { label: 'Network', color: 'text-terminal-yellow' },
  disk: { label: 'Disk & Storage', color: 'text-terminal-orange' },
  maintenance: { label: 'Maintenance', color: 'text-terminal-green' },
  security: { label: 'Security', color: 'text-terminal-red' },
  info: { label: 'Diagnostics', color: 'text-terminal-purple' },
}
